# Generated by Django 6.0.6 on 2026-07-08 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_summary', models.TextField(blank=True, default='', verbose_name='Professional Summary')),
                ('work_experiences', models.TextField(blank=True, default='', verbose_name='Work Experiences')),
                ('skills', models.TextField(blank=True, default='', verbose_name='Skills')),
                ('education', models.TextField(blank=True, default='', verbose_name='Education')),
                ('certificates', models.TextField(blank=True, default='', verbose_name='Certificates')),
                ('languages', models.TextField(blank=True, default='', verbose_name='Languages')),
                ('links', models.TextField(blank=True, default='', verbose_name='Links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
