# Generated by Django 6.0.6 on 2026-07-08 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Name'),
        ),
    ]
