# Generated by Django 6.0.6 on 2026-07-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_cv', '0002_generatedcv_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedcv',
            name='headings',
            field=models.TextField(blank=True, default='', verbose_name='Headings'),
        ),
    ]
