# Generated by Django 6.0.6 on 2026-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='resume',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Phone'),
        ),
    ]
